#!/usr/bin/with-contenv bash

echo "[Bind9] Starting..."

export HOME=/config

echo "[Bind9] Checking Bind9 config..."

if ! /usr/sbin/named-checkconf /etc/bind/named.conf ; then
	echo "[Bind9] Problem with Bind9 configuration - Bailing" >&2
	exit 1
fi

echo "[Bind9] Configs OK..."

/usr/sbin/named -u docker -c /etc/bind/named.conf -f
BEC=$?

if ! [ $BEC = 0 ]; then
	echo "[Bind9] Bind9 exited with ${BEC}"
	exit ${BEC} #exit with the same exit code as bind9
fi
